### ISSUE TITLE
need the relationship between dosages and administration route

### ISSUE THREAD

**Issue by 971105-vicky** [c-chen-ed5557/englishhealthdata#6]
for interactive design

**Comment by dodieli** [comment]
![image](https://user-images.githubusercontent.com/30234175/69557562-b8544000-0f9e-11ea-9bb4-2a62c425f5d1.png)
This is the pie chart that you need.

**Comment by 971105-vicky** [comment]
thanks but could you give me a more detailed one which includes all the administration routes?

**Comment by dodieli** [comment]
![image](https://user-images.githubusercontent.com/30234175/69558870-e20e6680-0fa0-11ea-9eae-6aa12c4a1993.png)

**Comment by 971105-vicky** [comment]
cheers!~
