### ISSUE TITLE
question for data comics(3)

### ISSUE THREAD

**Issue by 971105-vicky** [c-chen-ed5557/englishhealthdata#7]
How many endoscopies are performed each year in uk?

**Comment by dodieli** [comment]
In the United Kingdom (UK), around 2 million procedures are performed each year. Around 500 endoscopy units are registered with the Joint Advisory Group on GI Endoscopy (JAG), the organisation which oversees endoscopy quality in the UK.

And the reference for this is as below:

[Development of a national automated endoscopy database: The United Kingdom National Endoscopy Database (NED)](https://journals.sagepub.com/doi/full/10.1177/2050640619841539)
