### ISSUE TITLE
Discussion about the final report

### ISSUE THREAD

**Issue by dodieli** [c-chen-ed5557/englishhealthdata#8]
I think we should have a discussion about our final report. When are you guys free? And which way do you prefer, online or offline?

**Comment by 971105-vicky** [comment]
prefer face to face.

**Comment by 971105-vicky** [comment]
shall we meet at 13.00 tomorrow?

**Comment by randomgoose** [comment]
The main body of the report is finished. We need to remove redundant files and data in this repository and make it ready to be open and viewed by others. I'll raise another issue about this.
